services:
  - type: web
    name: partylink
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PARTYLINK_HTTP
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        sync: false
